databases:
  - name: library_app_production
    databaseName: library_app_production
    user: library_app
    plan: free

services:
  - type: web
    name: library_app
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    healthCheckPath: /health
    healthCheckTimeout: 5
    autoDeploy: false
    buildFilter:
      paths:
      - app/**
      - bin/**
      - config/**
      - db/**
      - lib/**
      - public/**
      - Gemfile
      - Gemfile.lock
      - Rakefile
      - config.ru
    envVars:
      - key: RAILS_ENV
        value: production
      - key: PORT
        value: 3000
      - key: RACK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: library_app_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_MAX_THREADS
        value: 5 